import Head from "next/head";
import { useEffect, useState } from "react";

type DataRes = {
  name: string;
};

export default function Home() {
  const [data, setData] = useState<DataRes | undefined>();

  useEffect(() => {
    fetch("/api/hello")
      .then((res) => res.json())
      .then((d) => {
        setData(d);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Hello {data?.name ?? "No World"}</div>
      </main>
    </>
  );
}
